"""
Report templates for Markdown output.
"""

REPORT_TEMPLATE = """# SudokuAI Evaluation Report

## Executive Summary

| Metric | Value |
|--------|-------|
| **Model** | {model_name} |
| **Provider** | {provider} |
| **Evaluation Date** | {evaluated_at} |
| **Total Games** | {total_games} |
| **Completed Games** | {completed_games} |
| **Correct Games** | {correct_games} |
| **Overall Accuracy** | {overall_accuracy:.1%} |
| **Total Time** | {total_time:.1f}s |

## Performance by Difficulty

| Difficulty | Games | Completed | Correct | Accuracy | Avg Moves | Avg Invalid |
|------------|-------|-----------|---------|----------|-----------|-------------|
{difficulty_table}

## Detailed Statistics

### Move Analysis
- **Total Moves**: {total_moves}
- **Valid Moves**: {valid_moves} ({valid_rate:.1%})
- **Invalid Moves**: {invalid_moves} ({invalid_rate:.1%})

### Time Analysis
- **Average Time per Game**: {avg_time_per_game:.1f}s
- **Average Moves per Game**: {avg_moves_per_game:.1f}

## Evaluation Configuration
- **Play Mode**: {play_mode}
- **Difficulties Tested**: {difficulties_tested}
- **Games per Difficulty**: {games_per_difficulty}

## Conclusions

{conclusions}

---
*Report generated by SudokuAI v{version}*
"""

DIFFICULTY_ROW_TEMPLATE = "| {difficulty} | {total} | {completed} | {correct} | {accuracy:.1%} | {avg_moves:.1f} | {avg_invalid:.1f} |"

COMPARISON_TEMPLATE = """# SudokuAI Model Comparison Report

## Overview

| Metric | {model1_name} | {model2_name} |
|--------|---------------|---------------|
| Overall Accuracy | {model1_accuracy:.1%} | {model2_accuracy:.1%} |
| Total Games | {model1_games} | {model2_games} |
| Correct Games | {model1_correct} | {model2_correct} |
| Total Time | {model1_time:.1f}s | {model2_time:.1f}s |

## Performance by Difficulty

| Difficulty | {model1_name} | {model2_name} | Winner |
|------------|---------------|---------------|--------|
{comparison_table}

## Analysis

{analysis}

---
*Report generated by SudokuAI v{version}*
"""
